### ISSUE TITLE
Compile tools for unix systems

### ISSUE THREAD

**Issue by emilyseville7cfg** [ColorfulSoft/DeOldify.NET#7]
- unix-compile.sh (Compile.bat alternative for Unix-based systems)
- unix-coonfig.rsb (Windows.rsb alternative for Unix-based systems)

**Comment by emilyseville7cfg** [comment]
I suggest not to use .bat files and use only Bash..

**Comment by GlebSBrykin** [comment]
> User can install cygwin to compile your project.

It's not a good idea to create additional dependencies when you can do without them. A separate instruction for building and running on Linux will be added in the near future.

**Comment by GlebSBrykin** [comment]
Personally, I'm not afraid of additional dependencies. But if we follow your logic, then the entire current project does not make sense, since the user can install Python on his PC with all the necessary libraries and run the original DeOldify. Moreover, all the components used there have been officially supporting Windows since Windows 7 for several years. Moreover, I successfully launched the original DeOldify on my Windows 7 PC. The meaning of this (and other ColorfulSoft's projects) is to simplify the process of using and developing neural networks under Windows and other operating systems as much as possible. For compilation DeOldify.NET in Windows, the tools that are installed in the system by default are sufficient. You are proposing to deliberately complicate the lives of users.
